### ISSUE TITLE
ox-hugo: TOML date problem?

### ISSUE THREAD

**Issue by kaushalmodi** [leetdatageek/leetdatageek#1]
Hello,

Google told me that someone wrote about `ox-hugo` today, and that's where I found your post: https://leetdatageek.github.io/posts/hugo-toml-date-problem/ :)

Glad to see that `ox-hugo` is working out for you (.. sort of?).

> The date format used by ox-hugo was not recognized by the TOML parser.

That post made me curious.. I am wondering why TOML dates won't work but YAML dates would.. because while a YAML date in front-matter is `date: 2018-05-20T22:51:00-03:00`, the TOML date is simply `date = 2018-05-20T22:51:00-03:00` (replaced ":" with " =").

It would be great if you can elaborate on that TOML date issue, and if possible open an issue on the `ox-hugo` repo with steps to reproduce.

*PS: I use TOML in all my front-matter for my blog posts without any problem.*

**Comment by leetdatageek** [comment]
Wow! Thank you for reaching out =). The error was pretty straightforward and it occurred after running the `hugo` command, so my bet is whatever is being used to transpile the `.md` file through the TOML config file is not recognizing the ISO format as it should. After changing to a YAML config file it worked, hence the little post the same day I was starting out with ox-hugo. The error is the following: `Expected 'Z' in ISO8601 datetime, but found '-' instead.`

**Comment by leetdatageek** [comment]
Oopsie doopsie! I got some stuff mixed up, the change on the config file was due to something I was trying to figure out about Google Analytics. Just changing `#+hugo_front_matter_format: yaml` solved the problem.

**Comment by kaushalmodi** [comment]
Hmm.. I'm willing to bet that your Hugo version is 0.1x or 0.2x something.. because I vaguely remember that Go TOML package used by Hugo to have this issue quite some time back.

**Comment by kaushalmodi** [comment]
OK, looks like I lost the bet.. your site source says that you used Hugo 0.37.1 :)

Can you post the markdown file with TOML date that gives that error?

**Comment by leetdatageek** [comment]
~elisp~ I mean org to TOML is as follows:

```emacs-lisp
** DONE HUGO date problems. TL;DR: switch to YAML                   :@emacs:
CLOSED: [2018-05-20 Sun 22:51]
```

```toml
+++
title = "HUGO date problems. TL;DR: switch to YAML"
author = ["myself"]
date = 2018-05-20T22:51:00-03:00
categories = ["emacs"]
draft = false
+++
```

**Comment by kaushalmodi** [comment]
I'm perplexed. The error message you posted was in a really old Hugo version. Can you print `hugo version` immediately after recreating that error, and paste the complete error and version here?

This is what I am talking about: https://github.com/gohugoio/hugo/issues/2100

I was able to regenerate your site from just the Org file, with all front matter in TOML. The only change was to comment out the line where you set YAML. I am using Hugo 0.40.3.

**Comment by leetdatageek** [comment]
Running `hugo version` returns `Hugo Static Site Generator v0.37.1 linux/amd64 BuildDate: ` (BuildDate is in fact empty.)
Since the HUGO doc says the built project is available to fetch through the Fedora package manager, I proceeded to do so. But now I think I may need to build it myself from the sauce.
```bash
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 28 (Twenty Eight)
Release:	28
Codename:	TwentyEight
```

**Comment by kaushalmodi** [comment]
> But now I think I may need to build it myself from the sauce.

You shouldn't need to. Couldn't you just download the generic Linux 64-bit binary, put it somewhere in your path and run it? (Or maybe simply put it in your Hugo site root dir and run directly with `./hugo`?)

Here's the [hugo 40.3 tar.gz][1]. Extracting and running should Just Work(TM). It's after all one of the selling points of Hugo.. a single **static** binary. 

So.. asking this one last time as I am now out of ideas.. you can *still* recreate that error on Hugo 0.37.1? 

If so, the only thing left to try is that latest 0.40.3 binary. 

I appreciate your patience trying to quench my curiosity. 

[1]: https://github.com/gohugoio/hugo/releases/download/v0.40.3/hugo_0.40.3_Linux-64bit.tar.gz

**Comment by kaushalmodi** [comment]
As I mentioned earlier, the same dates in TOML worked for me too.

[Here][1] I clone your site and commit the yaml->toml change on my throwaway gitlab repo (I'll delete it as soon as you review the changes).

I then build the site on Netlify (it's free) using hugo 0.40.3 and it builds fine -- see https://friendly-hamilton-ebbb9a.netlify.com/posts/hugo-toml-date-problem/.

<details>
  <summary>Build log on Netlify</summary>

```
10:33:02 AM: Build ready to start
10:33:04 AM: Fetching cached dependencies
10:33:04 AM: Failed to fetch cache, continuing with build
10:33:04 AM: Starting to prepare the repo for build
10:33:07 AM: No cached dependencies found. Cloning fresh repo
10:33:07 AM: git clone git@gitlab.com:kaushalmodi/hugo-throwaway-4
10:33:08 AM: Preparing Git Reference refs/heads/master
10:33:10 AM: Found netlify.toml. Overriding site configuration
10:33:10 AM: Different publish path detected, going to use the one specified in the toml file: 'public' versus '/' in the site
10:33:10 AM: Different build command detected, going to use the one specified in the toml file: 'hugo' versus '' in the site
10:33:10 AM: Starting build script
10:33:10 AM: Installing dependencies
10:33:11 AM: Downloading and installing node v8.11.2...
10:33:11 AM: Downloading https://nodejs.org/dist/v8.11.2/node-v8.11.2-linux-x64.tar.xz...
10:33:12 AM:   0.7%
10:33:12 AM: ###
10:33:12 AM:                                                                5.3%
10:33:12 AM: 
############
10:33:12 AM:                                                    17.8%
10:33:12 AM: 
###################
10:33:12 AM: ##                                                     30.3%
10:33:12 AM: 
#############################
10:33:12 AM:                                   40.6%
10:33:12 AM: 
###################################
10:33:12 AM:                                       49.5%
10:33:12 AM: 
###################
10:33:12 AM: ######################                                 58.3%
10:33:12 AM: 
#########################
10:33:12 AM: #######################                          67.3%
10:33:13 AM: 
###################################
10:33:13 AM: #####################                  78.1%
10:33:13 AM: #################################
10:33:13 AM: #############################            87.2%
10:33:13 AM: 
#####
10:33:13 AM: ################################################################     96.6%
10:33:13 AM: 
##############################
10:33:13 AM: ########################################## 100.0%
10:33:13 AM: Computing checksum with sha256sum
10:33:13 AM: Checksums matched!
10:33:16 AM: Now using node v8.11.2 (npm v5.6.0)
10:33:16 AM: Attempting ruby version 2.3.6, read from environment
10:33:17 AM: Using ruby version 2.3.6
10:33:17 AM: Using PHP version 5.6
10:33:17 AM: Installing Hugo 0.40.3
10:33:19 AM: Started restoring cached go cache
10:33:19 AM: Finished restoring cached go cache
10:33:19 AM: unset GOOS;
10:33:19 AM: unset GOARCH;
10:33:19 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
10:33:19 AM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
10:33:19 AM: go version >&2;
10:33:19 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
10:33:19 AM: go version go1.10 linux/amd64
10:33:19 AM: Installing missing commands
10:33:19 AM: Verify run directory
10:33:19 AM: Executing user command: hugo
10:33:19 AM: Building sites …
10:33:19 AM: 

10:33:19 AM:                    | EN
10:33:19 AM: +------------------+----+
10:33:19 AM:   Pages            | 13
10:33:19 AM:   Paginator pages  |  0
10:33:19 AM:   Non-page files   |  0
10:33:19 AM:   Static files     |  2
10:33:19 AM:   Processed images |  0
10:33:19 AM:   Aliases          |  0
10:33:19 AM:   Sitemaps         |  1
10:33:19 AM:   Cleaned          |  0
10:33:19 AM: Total in 36 ms
10:33:19 AM: Caching artifacts
10:33:19 AM: Started saving pip cache
10:33:19 AM: Finished saving pip cache
10:33:19 AM: Started saving emacs cask dependencies
10:33:20 AM: Finished saving emacs cask dependencies
10:33:20 AM: Started saving maven dependencies
10:33:20 AM: Finished saving maven dependencies
10:33:20 AM: Started saving boot dependencies
10:33:20 AM: Finished saving boot dependencies
10:33:20 AM: Started saving go dependencies
10:33:20 AM: Finished saving go dependencies
10:33:20 AM: Cached node version v8.11.2
10:33:20 AM: Build script success
10:33:20 AM: Starting to deploy site from 'public'
10:33:22 AM: Starting post processing
10:33:23 AM: Post processing done
10:33:23 AM: Site is live
10:33:28 AM: Finished processing build request in 24.362012292s
```
</details>

---

For reference, here is [your post with YAML front-matter][3], and then the [exact same in TOML][4].

[1]: https://gitlab.com/kaushalmodi/hugo-throwaway-4/commit/bdb73d7a3f60494cee33f4690a8c9d7c302a0694
[3]: https://raw.githubusercontent.com/leetdatageek/leetdatageek/381158c722223ad9b9ec8b5c67da23618e67a3c4/content/posts/hugo-toml-date-problem.md
[4]: https://gitlab.com/kaushalmodi/hugo-throwaway-4/raw/bdb73d7a3f60494cee33f4690a8c9d7c302a0694/content/posts/hugo-toml-date-problem.md

**Comment by leetdatageek** [comment]
I should be the one thanking you for the amazing piece of sw you created. It is a pleasure to use and this curiosity of yours I am certain is what made it come to fruition. 
I have good news! **The 0.40.3 release works like a charm!** :heart_eyes: :tada: I will update my blog post accordingly. Once again thank **YOU** for ox-hugo and for reaching out to help a random user on a trivial issue :smiley:

**Comment by kaushalmodi** [comment]
Interestingly, the official binary for Hugo 0.37.1 doesn't have that issue (I had tried that too). So something went wrong in the Fedora based build.. may be you should file that somewhere appropriate. I cannot verify the Fedora build as I don't use that OS. 

But glad that you got the TOML dates working. :)

And thanks for the kind words! :D
